[phases.setup]
nixPkgs = ["nodejs_20", "python311", "gcc", "gnumake", "pkg-config"]

[phases.install]
cmds = ["npm ci", "cd api && npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node api/server.js"